 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 15, in <module>
    detector = YOLOv5Detector(model_path='yolov5s.pt', device='cpu')
  File "/project/sandbox/user-workspace/plate_recognition/yolov5_utils.py", line 8, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_path, force_reload=True).to(self.device)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/torch/hub.py", line 647, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/torch/hub.py", line 680, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 135, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 54, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 18, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 15, in <module>
    detector = YOLOv5Detector(model_path='yolov5s.pt', device='cpu')
  File "/project/sandbox/user-workspace/plate_recognition/yolov5_utils.py", line 8, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_path, force_reload=True).to(self.device)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/torch/hub.py", line 647, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/torch/hub.py", line 680, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 135, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 54, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 15, in <module>
    detector = YOLOv5Detector(model_path='yolov5s.pt', device='cpu')
  File "/project/sandbox/user-workspace/plate_recognition/yolov5_utils.py", line 8, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_path, force_reload=True).to(self.device)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/torch/hub.py", line 647, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/torch/hub.py", line 680, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 135, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 54, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 2025-4-27 Python-3.10.13 torch-2.7.0+cu126 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape... 
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 2025-4-27 Python-3.10.13 torch-2.7.0+cu126 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape... 
 * Debugger is active!
 * Debugger PIN: 415-867-210
 * Detected change in '/root/.cache/torch/hub/ultralytics_yolov5_master/utils/metrics.py', reloading
 * Restarting with stat
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 2025-4-27 Python-3.10.13 torch-2.7.0+cu126 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape... 
 * Debugger is active!
 * Debugger PIN: 415-867-210
127.0.0.1 - - [27/Apr/2025 08:37:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 08:37:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 08:38:00] "[35m[1mPOST / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 110, in upload_file
    plate_text, boxed_filename = process_image(filepath)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 61, in process_image
    result = reader.readtext(processed_img)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 456, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 379, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 571, in get_image_list
    crop_img,ratio = compute_ratio_and_resize(crop_img,width,height,model_height)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 534, in compute_ratio_and_resize
    img = cv2.resize(img,(int(model_height*ratio),model_height),interpolation=Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
127.0.0.1 - - [27/Apr/2025 08:38:00] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:38:00] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 08:38:01] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:38:05] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:38:05] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:41:07] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/project/sandbox/user-workspace/plate_recognition/yolov8_utils.py', reloading
 * Restarting with stat
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 2025-4-27 Python-3.10.13 torch-2.7.0+cu126 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape... 
 * Debugger is active!
 * Debugger PIN: 415-867-210
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/gapi/__init__.py", line 323, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
127.0.0.1 - - [27/Apr/2025 08:47:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 08:47:39] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
WARNING ⚠️ NMS time limit 0.550s exceeded
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 08:48:00] "[35m[1mPOST / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 110, in upload_file
    plate_text, boxed_filename = process_image(filepath)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 61, in process_image
    result = reader.readtext(processed_img)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 456, in readtext
    horizontal_list, free_list = self.detect(img,
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 379, in recognize
    result = []
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 571, in get_image_list
    ratio = width/height
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 534, in compute_ratio_and_resize
    if len(mbox) != 1: # adjacent box in same line
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
127.0.0.1 - - [27/Apr/2025 08:48:01] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:48:01] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:48:01] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:48:03] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 08:48:18] "[35m[1mPOST / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 110, in upload_file
    plate_text, boxed_filename = process_image(filepath)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 61, in process_image
    result = reader.readtext(processed_img)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 456, in readtext
    horizontal_list, free_list = self.detect(img,
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 379, in recognize
    result = []
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 571, in get_image_list
    ratio = width/height
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 534, in compute_ratio_and_resize
    if len(mbox) != 1: # adjacent box in same line
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
127.0.0.1 - - [27/Apr/2025 08:48:18] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:48:18] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:48:19] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * To enable the debugger you need to enter the security pin:
 * Debugger pin code: 415-867-210
127.0.0.1 - - [27/Apr/2025 08:49:30] "GET /?__debugger__=yes&cmd=printpin&s=8hMHN35kjiuImVm5AeLt HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 08:50:00] "GET /?__debugger__=yes&cmd=pinauth&pin=5090&s=8hMHN35kjiuImVm5AeLt HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 08:52:35] "GET / HTTP/1.1" 200 -
/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 08:52:53] "[35m[1mPOST / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 110, in upload_file
    plate_text, boxed_filename = process_image(filepath)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 61, in process_image
    result = reader.readtext(processed_img)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 456, in readtext
    horizontal_list, free_list = self.detect(img,
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 379, in recognize
    result = []
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 571, in get_image_list
    ratio = width/height
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 534, in compute_ratio_and_resize
    if len(mbox) != 1: # adjacent box in same line
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
127.0.0.1 - - [27/Apr/2025 08:52:54] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:52:54] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:52:54] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:52:56] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 08:52:57] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/project/sandbox/user-workspace/plate_recognition/app.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/gapi/__init__.py", line 323, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
Traceback (most recent call last):
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 3, in <module>
    import cv2
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/cv2/gapi/__init__.py", line 323, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8s.pt to 'yolov8s.pt'...
  0%|          | 0.00/21.5M [00:00<?, ?B/s] 55%|█████▌    | 11.9M/21.5M [00:00<00:00, 123MB/s]100%|██████████| 21.5M/21.5M [00:00<00:00, 132MB/s]
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 415-867-210
127.0.0.1 - - [27/Apr/2025 09:13:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 09:13:25] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -

0: 288x640 (no detections), 1439.7ms
Speed: 31.9ms preprocess, 1439.7ms inference, 2.5ms postprocess per image at shape (1, 3, 288, 640)
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 09:13:43] "[35m[1mPOST / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 115, in upload_file
    plate_text, boxed_filename = process_image(filepath)
  File "/project/sandbox/user-workspace/plate_recognition/app.py", line 66, in process_image
    result = reader.readtext(pil_img)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/easyocr.py", line 454, in readtext
    img, img_cv_grey = reformat_input(image)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/easyocr/utils.py", line 767, in reformat_input
    raise ValueError('Invalid input type. Supporting format = string(file path or url), bytes, numpy array')
ValueError: Invalid input type. Supporting format = string(file path or url), bytes, numpy array
127.0.0.1 - - [27/Apr/2025 09:13:43] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 09:13:43] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 09:13:44] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 09:13:46] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 09:13:47] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [27/Apr/2025 09:16:52] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 415-867-210
 * Detected change in '/project/sandbox/user-workspace/plate_recognition/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 415-867-210
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
127.0.0.1 - - [27/Apr/2025 09:20:12] "GET / HTTP/1.1" 200 -

0: 288x640 (no detections), 1536.4ms
Speed: 332.1ms preprocess, 1536.4ms inference, 3.9ms postprocess per image at shape (1, 3, 288, 640)
Using CPU. Note: This module is much faster with a GPU.
/home/codespace/.python/current/lib/python3.10/site-packages/torch/utils/data/dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
127.0.0.1 - - [27/Apr/2025 09:20:41] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 09:20:42] "[33mGET /static/uploads/boxed_0632.jpeg HTTP/1.1[0m" 404 -
127.0.0.1 - - [27/Apr/2025 09:27:08] "GET / HTTP/1.1" 200 -

0: 384x640 (no detections), 633.9ms
Speed: 44.1ms preprocess, 633.9ms inference, 3.2ms postprocess per image at shape (1, 3, 384, 640)
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 09:27:28] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 09:27:28] "[33mGET /static/uploads/boxed_Grayscale_image.jpg HTTP/1.1[0m" 404 -
127.0.0.1 - - [27/Apr/2025 09:27:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 11:41:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 11:41:11] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -

0: 384x640 (no detections), 414.8ms
Speed: 49.6ms preprocess, 414.8ms inference, 4.8ms postprocess per image at shape (1, 3, 384, 640)
Using CPU. Note: This module is much faster with a GPU.
127.0.0.1 - - [27/Apr/2025 11:41:33] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 11:41:34] "[33mGET /static/uploads/boxed_number_plate_BW.jpeg HTTP/1.1[0m" 404 -
127.0.0.1 - - [27/Apr/2025 11:41:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2025 12:52:14] "GET / HTTP/1.1" 200 -
